# Generated by Django 4.1.3 on 2024-01-06 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='camera',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='camera_settings',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
