# Generated by Django 4.1.3 on 2024-01-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_followerscount_alter_like_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
