# Generated by Django 4.1.3 on 2024-01-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_reports',
            field=models.IntegerField(default=0),
        ),
    ]
